### ISSUE TITLE
Weird aether error

### ISSUE THREAD

**Issue by stathissideris** [juxt/pack.alpha#15]
I ran this:

```
clj -A:pack mach.pack.alpha.capsule uberjar.jar --application-id eggshell -m eggshell.main
```

and got:

```
Exception in thread "main" org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.maven.resolver:maven-resolver-transport-wagon:jar:1.1.1
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:323)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:192)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:253)
	at clojure.tools.deps.alpha.extensions.maven$eval668$fn__670.invoke(maven.clj:77)
	at clojure.lang.MultiFn.invoke(MultiFn.java:243)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:170)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:152)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:215)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:197)
	at mach.pack.alpha.capsule$_main.invokeStatic(capsule.clj:132)
	at mach.pack.alpha.capsule$_main.doInvoke(capsule.clj:109)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact org.apache:apache:pom:19
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:178)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:224)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1051)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:829)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:331)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:314)
	... 20 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.apache:apache:pom:19
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:174)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache:apache:pom:19
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:412)
	... 28 more
```

This is my deps.edn:

```
{:deps
 {org.clojure/tools.analyzer.jvm {:mvn/version "0.7.2"}
  seesaw                         {:mvn/version "1.5.0"}
  rakk                           {:git/url "https://github.com/stathissideris/rakk"
                                  :sha     "a4b5717086e66989856a45a1f6e5d04628e6aec3"}
  cross-parinfer                 {:mvn/version "1.4.5"}
  org.clojure/tools.deps.alpha   {:git/url "https://github.com/clojure/tools.deps.alpha.git"
                                  :sha     "d492e97259c013ba401c5238842cd3445839d020"}}
 :aliases
 {:repl {:extra-deps {org.clojure/tools.nrepl {:mvn/version "0.2.13"}
                      cider/cider-nrepl       {:mvn/version "0.17.0"}}}
  :pack {:extra-deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git"
                                       :sha "1d455f6c591f440560c57a29e6d930004d735dcf"}}
         :main-opts ["-m"]}}}
```

**Comment by stathissideris** [comment]
Is there proposed solution to add clojure itself to deps.edn? If yes, it didn't work for me!

**Comment by SevereOverfl0w** [comment]
There's some internal debate about whether Clojure should be an automatically provided dependency or not. For now, you get Clojure 1.9 in `/usr/lib/clojure/deps.edn`.

Pack only looks at a single deps.edn, there's two reasons for this:

1. Support running against a deps.edn that doesn't contain pack
2. t.d.a doesn't expose an API which names the files, so I have to evaluate the system deps.edn, the user deps.edn and also the deps.edn specified, or only the deps.edn specified

I really want to ensure deps.edn files are reproducible, which is difficult if I can't avoid bringing in the user's deps.edn file.

**Comment by stathissideris** [comment]
ok I get it, thanks for explaining, but adding clojure didn't fix it for me, any other ideas?

**Comment by SevereOverfl0w** [comment]
I suspect adding:

```
  :mvn/repos {
    "central" {:url "https://repo1.maven.org/maven2/"}
    "clojars" {:url "https://repo.clojars.org/"}
  }
```

is the fix here

**Comment by stathissideris** [comment]
That fixed it for me, many thanks! I think the conclusion here is that the deps.edn needs to be completely self-sufficient for pack to succeed.
