### ISSUE TITLE
Artifact resolution fails as soon as I depend on net.mikera/imagez

### ISSUE THREAD

**Issue by kenranunderscore** [juxt/pack.alpha#23]
This seems to be related to #7, at least the workaround is the same. Here is a minimal deps.edn:

```clojure
{;;:mvn/repos {"central" {:url "https://repo1.maven.org/maven2/"}
             ;;"clojars" {:url "https://repo.clojars.org/"}}
 :deps {org.clojure/clojure {:mvn/version "1.9.0"}
        net.mikera/imagez {:mvn/version "0.12.0"}
        }
 :paths ["src" "."]
 :aliases {:run {:main-opts ["-m" "mikpom.main"]}
           :uberjar {:main-opts ["-m" "mach.pack.alpha.capsule" "deps.edn" "foo.jar"]
                     :extra-deps
                     {pack/pack.alpha
                      {:git/url "git@github.com:juxt/pack.alpha.git"
                       :sha "e6d0691c5f58135e1ef6fb1c9dda563611d36205"}}}}}

```

I get the following error:
```
Exception in thread "main" org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for net.mikera:imagez:jar:0.12.0
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:329)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:253)
	at clojure.tools.deps.alpha.extensions.maven$eval823$fn__825.invoke(maven.clj:55)
	at clojure.lang.MultiFn.invoke(MultiFn.java:243)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:155)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:137)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:191)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:182)
	at mach.pack.alpha.capsule$_main.invokeStatic(capsule.clj:157)
	at mach.pack.alpha.capsule$_main.doInvoke(capsule.clj:150)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact net.mikera:mikera-pom:pom:0.6.0 in clojars.org (http://clojars.org/repo)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:177)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:226)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1000)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:800)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:329)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	... 20 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact net.mikera:mikera-pom:pom:0.6.0 in clojars.org (http://clojars.org/repo)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:173)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact net.mikera:mikera-pom:pom:0.6.0 in clojars.org (http://clojars.org/repo)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	... 28 more
```

If I uncomment the first two lines, it works again. I'd just like to understand if I'm doing something wrong or if there is a problem elsewhere. Admittedly, I just started using the CLI and deps.edn yesterday, so I might just be missing something.

Btw, I stumbled over an analogous error elsewhere with an older version of `mikera-pom`, but it seems to have been an issue with `lein-npm`.

**Comment by kenranunderscore** [comment]
As @SevereOverfl0w pointed out to me on the Clojure Slack, I was using an old (copied) version of pack. Using the latest commit `595388c5b909759445a92a19192df50e427aa9a5` fixes it for me in the minimal example. Sorry and thanks!
