### ISSUE TITLE
Why is this trying to download Clojure 1.7.0?

### ISSUE THREAD

**Issue by mtnygard** [juxt/pack.alpha#3]
I'm attempting to use Pack to make an uberjar for AWS Lambda. My deps.edn does not have any direct reference to Clojure 1.7.0:

deps.edn
``` 
{:paths ["src/main/clojure"]
 :deps
 {com.datomic/client-cloud        {:mvn/version "0.8.50"}
  org.clojure/data.json           {:mvn/version "0.2.6"}
  com.amazonaws/aws-lambda-java-core   {:mvn/version "1.2.0"}
  com.amazonaws/aws-lambda-java-events {:mvn/version "2.0.2"}}}
```

This is the result I get.

```
mtnygard@spark:roc.platform.station-health-dl (master *%)$ cat bin/uberjar
#! /bin/bash
clj -Sdeps '{:deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git" :sha "eed89476315661e2389d5d078ec17375bec3efa5"}}}' -m mach.pack.alpha.aws-lambda deps.edn roc.station-health.zip target/classes
mtnygard@spark:roc.platform.station-health-dl (master *%)$ bin/uberjar
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/mtnygard/.m2/repository/org/slf4j/slf4j-nop/1.6.2/slf4j-nop-1.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/mtnygard/.m2/repository/ch/qos/logback/logback-classic/1.0.12/logback-classic-1.0.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
Exception in thread "main" org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.clojure:clojure:jar:1.7.0
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:260)
        at clojure.tools.deps.alpha.extensions.maven$eval834$fn__836.invoke(maven.clj:71)
        at clojure.lang.MultiFn.invoke(MultiFn.java:243)
        at clojure.tools.deps.alpha$lib_paths$fn__306.invoke(alpha.clj:175)
        at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
        at clojure.core.protocols$fn__7839.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__7839.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__7781$G__7776__7794.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6748)
        at clojure.core$reduce.invoke(core.clj:6730)
        at clojure.tools.deps.alpha$lib_paths.invokeStatic(alpha.clj:171)
        at clojure.tools.deps.alpha$lib_paths.invoke(alpha.clj:169)
        at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:192)
        at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:182)
        at mach.pack.alpha.aws_lambda$_main.invokeStatic(aws_lambda.clj:110)
        at mach.pack.alpha.aws_lambda$_main.doInvoke(aws_lambda.clj:103)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.core$apply.invokeStatic(core.clj:657)
        at clojure.main$main_opt.invokeStatic(main.clj:317)
        at clojure.main$main_opt.invoke(main.clj:313)
        at clojure.main$main.invokeStatic(main.clj:424)
        at clojure.main$main.doInvoke(main.clj:387)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:702)
        at clojure.main.main(main.java:37)
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.clojure:clojure:jar:1.7.0
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:412)
        ... 28 more
```

I'm not sure what's causing the attempt to pull in 1.7.

**Comment by mtnygard** [comment]
If I explicitly add my Clojure version to deps.edn, then I get a clean build. But I was under the impression that we wouldn't want to add Clojure everywhere in this new world.

**Comment by SevereOverfl0w** [comment]
I started this thinking it might be due to pack being co-hosted with your project, but I'm certain it isn't, the error doesn't add up.

Because of how tools.deps.alpha works, your project must work under `clj -Srepro` in order to work. I couldn't run your project, as I don't have datomic-cloud locally.

This has highlighted to me that `clj -Srepro` actually doesn't include any remote maven repositories, so you need to run `clj` once locally in order to fetch it into `~/.m2/`.

I'm on the fence here about what I want to do. It's important to me that dependencies from the user's global files (i.e. /usr/lib/clojure/deps.edn) do not impact how the packaging is built. I do want the `:mvn/repositories` from that file to be considered though.

For now, the workaround is to `clj` once locally then do the pack build after. Or add an explicit dependency that's already been fetched.

I apologise for this.

**Comment by mtnygard** [comment]
Definitely understand and agree about excluding extra-project libraries from /user/lib/clojure/deps.edn, ~/.clojure/deps.edn, etc.

I don't think that's affecting my project. I can definitely run with `-Srepro`.

FWIW, com.datomic/client-cloud is in Maven central.

You may already have spotted this, but I just found that if I add `:mvn/repos {"central" {:url "https://repo1.maven.org/maven2"}}` to my deps.edn, then I can resolve Clojure 1.7.0. That lets me use the (undocumented) function `clojure.tools.deps.alpha/print-tree` to see the following:

```
org.clojure/data.json 0.2.6                                            
com.amazonaws/aws-lambda-java-core 1.2.0                               
expound 0.5.0                                                          
com.amazonaws/aws-lambda-java-events 2.0.2                             
com.datomic/client-cloud 0.8.50                                        
  com.cognitect/anomalies 0.1.12                                       
  com.datomic/client 0.8.40                                            
    com.cognitect/http-client 0.1.83                                   
      org.eclipse.jetty/jetty-http 9.3.7.v20160115                     
      org.eclipse.jetty/jetty-util 9.3.7.v20160115                     
      org.eclipse.jetty/jetty-client 9.3.7.v20160115                   
        org.eclipse.jetty/jetty-io 9.3.7.v20160115                     
  com.datomic/client-impl-shared 0.8.34                                
    com.cognitect/hmac-authn 0.1.194                                   
      commons-codec/commons-codec 1.10                                 
    com.cognitect/transit-clj 0.8.285                                  
      com.cognitect/transit-java 0.8.311                               
        org.msgpack/msgpack 0.6.10                                     
          com.googlecode.json-simple/json-simple 1.1.1                 
          org.javassist/javassist 3.18.1-GA                            
  com.cognitect/s3-creds 0.1.22                                        
    com.fasterxml.jackson.core/jackson-core 2.8.1                      
    org.clojure/core.cache 0.6.5                                       
      org.clojure/data.priority-map 0.0.7                              
  com.datomic/s3-access-keys 0.1.6                                     
  org.clojure/core.async 0.3.442                                       
    org.clojure/clojure 1.7.0                                          
    org.clojure/tools.analyzer.jvm 0.7.0                               
      org.clojure/tools.analyzer 0.6.9                                 
      org.clojure/tools.reader 1.0.0-beta4                             
      org.clojure/core.memoize 0.5.9                                   
      org.ow2.asm/asm-all 4.2                                          
  com.amazonaws/aws-java-sdk-s3 1.11.210                               
    com.amazonaws/jmespath-java 1.11.210                               
      com.fasterxml.jackson.core/jackson-databind 2.6.7.1              
        com.fasterxml.jackson.core/jackson-annotations 2.6.0           
    com.amazonaws/aws-java-sdk-core 1.11.210                           
      joda-time/joda-time 2.8.1                                        
      com.fasterxml.jackson.dataformat/jackson-dataformat-cbor 2.6.7   
      software.amazon.ion/ion-java 1.0.2                               
      org.apache.httpcomponents/httpclient 4.5.2                       
        org.apache.httpcomponents/httpcore 4.4.4                       
        commons-logging/commons-logging 1.2                            
    com.amazonaws/aws-java-sdk-kms 1.11.210                            
```

So I can definitively say that Pack is *not* responsible for pulling in Clojure 1.7!

Maybe all that's needed is a comment in the Readme about making reproducible uberjars by including your repos in the project's own deps.edn file?

**Comment by SevereOverfl0w** [comment]
The behaviour of -Srepro has changed to include the global install file, but not the one in `$HOME`. https://github.com/clojure/brew-install/commit/2a0b87be690de827a110d30234d2d4ba3ba0388d

I can emulate it by doing something similar to https://github.com/clojure/tools.deps.alpha/blob/88f8e4f0113ba555c3c667bd5fbf60f3887f8140/src/main/clojure/clojure/tools/deps/alpha/reader.clj#L18-L28 but additionally specifying `-Srepro`.

I'm going to take some time and try fix this on my morning commute tomorrow.

**Comment by SevereOverfl0w** [comment]
Try `d305c48386f73ebb60df30ba16d0a7e350a0d6c8` for pack. I'll push a new version later which handles this for both the jcl and capsule loaders, but this appears to resolve it for lambda. I've not had much time to work on it unfortunately.

I'm not entirely happy with it, because it brings in the local deps.edn for you, and that's not going to go well with the existing architecture of being able to run this from anywhere.

The way you're running it will work with this sha though.

**Comment by mtnygard** [comment]
I appreciate the work you're putting in, but my problem is already solved. I'm actually happier with a reproducible build that has the repos listed explicitly in the project's own `deps.edn` file. (Unless I'm missing something?)
