### ISSUE TITLE
building uberjar error: duplicate entry: .DS_Store

### ISSUE THREAD

**Issue by pbaille** [juxt/pack.alpha#62]
When trying to build an uberjar with this comand:

`clj -A:pack -m mach.pack.alpha.capsule myproject.jar -m my.project.entry.point`

I'm facing this error:

```
Exception in thread "process-height-1" java.util.zip.ZipException: duplicate entry: .DS_Store
        at java.util.zip.ZipOutputStream.putNextEntry(ZipOutputStream.java:232)
        at java.util.jar.JarOutputStream.putNextEntry(JarOutputStream.java:109)
        at mach.pack.alpha.impl.vfs$eval1393$fn__1394$fn__1399.invoke(vfs.clj:174)
        at mach.pack.alpha.impl.vfs$eval1393$fn__1394.invoke(vfs.clj:164)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at mach.pack.alpha.impl.vfs$write_vfs$fn__1437.invoke(vfs.clj:221)
        at mach.pack.alpha.impl.vfs$process_height$fn__1330.invoke(vfs.clj:68)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.lang.Thread.run(Thread.java:745)
```
the pack dependency is in my `~/.clojure/deps.edn`
```
{:aliases 
  {
  ...
  :pack
  {:extra-deps
   {pack/pack.alpha
    {:git/url "https://github.com/juxt/pack.alpha.git"
     :sha "2769a6224bfb938e777906ea311b3daf7d2220f5"}}}
   ...}
}
```

**Comment by SevereOverfl0w** [comment]
Makes sense. Duplicate entries are an error, and that's intentional.

This message could be better to point you at the break. Also in this specific case there's the fact that this is a garbage file that you don't want.

**Comment by pbaille** [comment]
Yes it is a garbage file, specific to osx I think. I'm surprised that anybody else ran into this error since DS_Store files seems to be automatically generated by osx.

**Comment by SevereOverfl0w** [comment]
I just realized what's happening, I was a little misleading before.

You have multiple :paths in your project, and in two of them you have the same file. There's no sensible decision that can be made here really.

I could restructure to load in a project directory by directory, which would allow for projects with duplicate files.

Currently not supported though, and this issue wouldn't be motivation for that.

**Comment by SevereOverfl0w** [comment]
Capsule is no longer supported.  I believe the new onejar implementation solves this problem.

If someone runs across a similar issue with any of the new implementations please open an issue.
