### ISSUE TITLE
NullPointerException with specific depedency

### ISSUE THREAD

**Issue by konstantinaBS** [juxt/pack.alpha#64]
Hello!

The following exception is thrown when I add metasoarous/oz in deps.edn and trying to build an uberjar: 
```
Exception in thread "main" java.lang.NullPointerException
	at clojure.tools.deps.alpha.util.maven$make_session.invokeStatic(maven.clj:141)
	at clojure.tools.deps.alpha.util.maven$make_session.invoke(maven.clj:138)
	at clojure.tools.deps.alpha.extensions.maven$eval709$fn__711.invoke(maven.clj:76)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:179)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:161)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:224)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:206)
	at mach.pack.alpha.impl.tools_deps$parse_deps_map.invokeStatic(tools_deps.clj:77)
	at mach.pack.alpha.impl.tools_deps$parse_deps_map.invoke(tools_deps.clj:71)
	at mach.pack.alpha.capsule$_main.invokeStatic(capsule.clj:125)
	at mach.pack.alpha.capsule$_main.doInvoke(capsule.clj:101)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

Bellow is a minimal deps.edn that reproduces the issue:
```
{:deps {metasoarous/oz {:mvn/version "1.6.0-alpha5"}}
 :aliases {:pack {:extra-deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git"
                                                :sha "81b9e47d992b17aa3e3af1a47aed1f0287ebe9b8"}}
                  :main-opts  ["-m"
                               "mach.pack.alpha.capsule"
                               "app.jar"
                               "-e" "target"
                               "--application-id" "app"
                               "--application-version" "\"1.0.0\""]}}}
```

**Comment by SevereOverfl0w** [comment]
Just looking at this now, but I think master _may_ fix it as it bumped the t.d.a version. I forgot that I'd not merged that. Apologies.

**Comment by SevereOverfl0w** [comment]
Interestingly, this doesn't re-occur when calling pack from the REPL. Only via the CLI?!

**Comment by SevereOverfl0w** [comment]
`(maven/make-system)` is returning `nil`, hence :boom:

**Comment by SevereOverfl0w** [comment]
Digging through the java, this doesn't make a whole lot of sense :) This has been reported before to tools.deps.alpha at https://clojurians.zulipchat.com/#narrow/stream/180378-slack-archive/topic/tools-deps/near/159950271

**Comment by SevereOverfl0w** [comment]
With some well-placed debugging into maven/aether I got this stack trace that was being swallowed:

```
java.lang.ClassCastException: Cannot cast org.apache.maven.repository.internal.DefaultVersionResolver to org.eclipse.aether.impl.VersionResolver
	at java.lang.Class.cast(Class.java:3369)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance(DefaultServiceLocator.java:167)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances(DefaultServiceLocator.java:140)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance(DefaultServiceLocator.java:125)
	at org.eclipse.aether.impl.DefaultServiceLocator.getService(DefaultServiceLocator.java:282)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.initService(DefaultRepositorySystem.java:145)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance(DefaultServiceLocator.java:170)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances(DefaultServiceLocator.java:140)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance(DefaultServiceLocator.java:125)
	at org.eclipse.aether.impl.DefaultServiceLocator.getService(DefaultServiceLocator.java:282)
	at clojure.tools.deps.alpha.util.maven$make_system.invokeStatic(maven.clj:154)
	at clojure.tools.deps.alpha.util.maven$make_system.invoke(maven.clj:152)
	at clojure.tools.deps.alpha.extensions.maven$eval774$fn__776$fn__778.invoke(maven.clj:93)
	at clojure.tools.deps.alpha.util.session$retrieve.invokeStatic(session.clj:23)
	at clojure.tools.deps.alpha.util.session$retrieve.invoke(session.clj:14)
	at clojure.tools.deps.alpha.extensions.maven$eval774$fn__776.invoke(maven.clj:93)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$fn__1161.invoke(alpha.clj:184)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:183)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:164)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:231)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:213)
	at mach.pack.alpha.impl.tools_deps$parse_deps_map.invokeStatic(tools_deps.clj:95)
	at mach.pack.alpha.impl.tools_deps$parse_deps_map.invoke(tools_deps.clj:88)
	at mach.pack.alpha.capsule$_main.invokeStatic(capsule.clj:109)
	at mach.pack.alpha.capsule$_main.doInvoke(capsule.clj:104)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
java.lang.NullPointerException: version resolver cannot be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.setVersionResolver(DefaultRepositorySystem.java:170)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.initService(DefaultRepositorySystem.java:145)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance(DefaultServiceLocator.java:170)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances(DefaultServiceLocator.java:140)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance(DefaultServiceLocator.java:125)
	at org.eclipse.aether.impl.DefaultServiceLocator.getService(DefaultServiceLocator.java:282)
	at clojure.tools.deps.alpha.util.maven$make_system.invokeStatic(maven.clj:154)
	at clojure.tools.deps.alpha.util.maven$make_system.invoke(maven.clj:152)
	at clojure.tools.deps.alpha.extensions.maven$eval774$fn__776$fn__778.invoke(maven.clj:93)
	at clojure.tools.deps.alpha.util.session$retrieve.invokeStatic(session.clj:23)
	at clojure.tools.deps.alpha.util.session$retrieve.invoke(session.clj:14)
	at clojure.tools.deps.alpha.extensions.maven$eval774$fn__776.invoke(maven.clj:93)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$fn__1161.invoke(alpha.clj:184)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:183)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:164)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:231)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:213)
	at mach.pack.alpha.impl.tools_deps$parse_deps_map.invokeStatic(tools_deps.clj:95)
	at mach.pack.alpha.impl.tools_deps$parse_deps_map.invoke(tools_deps.clj:88)
	at mach.pack.alpha.capsule$_main.invokeStatic(capsule.clj:109)
	at mach.pack.alpha.capsule$_main.doInvoke(capsule.clj:104)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

**Comment by SevereOverfl0w** [comment]
In my REPL org.apache.maven.repository.internal.DefaultVersionResolver is the version resolver. So somehow that's set in one context, and not another!

**Comment by SevereOverfl0w** [comment]
https://github.com/apache/maven/blob/2d0c3bc75b9fa191846ce5b43f6900701a1bf825/maven-resolver-provider/src/main/java/org/apache/maven/repository/internal/MavenRepositorySystemUtils.java this is what is used by tools.deps to create a session, and the locator it creates is somehow missing a version resolver

**Comment by SevereOverfl0w** [comment]
I missed it, the bug is right above ^^

```
Getting instances for interface org.eclipse.aether.impl.VersionResolver
java.lang.ClassCastException: Cannot cast org.apache.maven.repository.internal.DefaultVersionResolver to org.eclipse.aether.impl.VersionResolver
	at java.lang.Class.cast(Class.java:3369)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance(DefaultServiceLocator.java:167)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances(DefaultServiceLocator.java:140)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance(DefaultServiceLocator.java:125)
	at org.eclipse.aether.impl.DefaultServiceLocator.getService(DefaultServiceLocator.java:282)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.initService(DefaultRepositorySystem.java:145)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance(DefaultServiceLocator.java:170)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances(DefaultServiceLocator.java:140)
	at org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance(DefaultServiceLocator.java:125)
	at org.eclipse.aether.impl.DefaultServiceLocator.getService(DefaultServiceLocator.java:282)
	at clojure.tools.deps.alpha.util.maven$make_system.invokeStatic(maven.clj:154)
	at clojure.tools.deps.alpha.util.maven$make_system.invoke(maven.clj:152)
	at clojure.tools.deps.alpha.extensions.maven$eval774$fn__776$fn__778.invoke(maven.clj:93)
	at clojure.tools.deps.alpha.util.session$retrieve.invokeStatic(session.clj:23)
	at clojure.tools.deps.alpha.util.session$retrieve.invoke(session.clj:14)
	at clojure.tools.deps.alpha.extensions.maven$eval774$fn__776.invoke(maven.clj:93)
	at clojure.lang.MultiFn.invoke(MultiFn.java:244)
	at clojure.tools.deps.alpha$expand_deps$fn__1161.invoke(alpha.clj:184)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:183)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:164)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:231)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:213)
	at mach.pack.alpha.impl.tools_deps$parse_deps_map.invokeStatic(tools_deps.clj:95)
	at mach.pack.alpha.impl.tools_deps$parse_deps_map.invoke(tools_deps.clj:88)
	at mach.pack.alpha.capsule$_main.invokeStatic(capsule.clj:109)
	at mach.pack.alpha.capsule$_main.doInvoke(capsule.clj:104)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.main$main_opt.invokeStatic(main.clj:491)
	at clojure.main$main_opt.invoke(main.clj:487)
	at clojure.main$main.invokeStatic(main.clj:598)
	at clojure.main$main.doInvoke(main.clj:561)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:705)
	at clojure.main.main(main.java:37)
```

**Comment by SevereOverfl0w** [comment]
I've gotten to the bottom of it. Loading tools.deps.alpha and oz at the same time fails. Pack can be removed from the equation!

**Comment by stathissideris** [comment]
Wow, so it's something to do with t.d.a or the way oz is packaged, bizarre! We should probably raise it with t.d.a. Simply running `clojure` with this deps.edn does not result in any problems, what would be the minimal use case to demonstrate this?

```
{:deps {metasoarous/oz               {:mvn/version "1.6.0-alpha3"}
        org.clojure/tools.deps.alpha {:mvn/version "0.7.549"}}}
```

**Comment by SevereOverfl0w** [comment]
I have raised it with them, that's the minimal deps.edn though, yeah. Here's the code:

```
;; src/io/dominic/tda_npe/core.clj
(ns io.dominic.tda-npe.core
  (:require
    [clojure.tools.deps.alpha :as tools.deps]))

(def deps-map
  '{:paths ["src"]
    :deps {org.clojure/clojure #:mvn{:version "1.9.0"} }
    :mvn/repos {"central" {:url "https://repo1.maven.org/maven2/"}
                "clojars" {:url "https://repo.clojars.org/"}}})

(defn -main
  [& _]
  (tools.deps/resolve-deps deps-map {}))
```

oz is packaged as an uberjar, as such it seems to have included copies of things like cheshire and timbre.  Something to be cautious of :).

I have found duplicates of classes on the classpath relating to maven, so I'm going to dig into that.

**Comment by SevereOverfl0w** [comment]
Here's the dupes relating to the version resolver.

```
/home/dominic/.m2/repository/org/apache/maven/maven-aether-provider/3.0.4/maven-aether-provider-3.0.4.jar: org/apache/maven/repository/internal/DefaultVersionResolver.class
/home/dominic/.m2/repository/org/apache/maven/maven-resolver-provider/3.5.2/maven-resolver-provider-3.5.2.jar: org/apache/maven/repository/internal/DefaultVersionResolver.class
```

**Comment by SevereOverfl0w** [comment]
Got it. Use this for oz instead:

```
metasoarous/oz {:mvn/version "1.6.0-alpha5"
                  :exclusions [org.apache.maven/maven-aether-provider]}
```

**Comment by konstantinaBS** [comment]
Yeap, it worked! :smile: 
Thanks a lot @SevereOverfl0w for your time and investigation! 
Much appreciated! :)

**Comment by SevereOverfl0w** [comment]
Great :) I've mentioned this upstream to t.d.a as well. I don't think there's anything they can do.

As a note, I'm not certain oz will work with that exclusion, you may wish to add that version of the oz dependency to the pack alias. That should mean it's only excluded when building with pack, and is still included in your application.

**Comment by stathissideris** [comment]
I'll liaise with Christopher Small (the oz guy) to see if he'll agree to re-publish oz as a regular jar.

**Comment by SevereOverfl0w** [comment]
Using :deps instead of :extra-deps in your alias on the latest clj version will fix this more easily.

**Comment by konstantinaBS** [comment]
Thanks a lot @SevereOverfl0w!
Excluding aether solved the issue, however it turned out that there was also a problem with the js build because of the rest oz dependencies so we ended up removing it completely :(
At least until publishing a non-uberjar version as @stathissideris suggested above.
