### ISSUE TITLE
Unresolvable artifact error

### ISSUE THREAD

**Issue by solussd** [juxt/pack.alpha#7]
Edited: reduced deps map to minimum required to reproduce.

Running `clj -A:pack mach.pack.alpha.aws-lambda deps.edn lambda.zip build_dir` (or capsule)
with deps.edn:
```
{:deps {javax.servlet/javax.servlet-api {:mvn/version "3.1.0"}}
 :paths ["src"]
 :aliases {:pack {:extra-deps {pack/pack.alpha {:git/url "https://github.com/juxt/pack.alpha.git"
                                                :sha "c046f1ad118911ffb161a347d909ecc43c75af4f"}}
                  :main-opts ["-m"]}}}
```

throws:
```
Exception in thread "main" org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for javax.servlet:javax.servlet-api:jar:3.1.0
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:329)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:198)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.readArtifactDescriptor(DefaultRepositorySystem.java:253)
	at clojure.tools.deps.alpha.extensions.maven$eval823$fn__825.invoke(maven.clj:55)
	at clojure.lang.MultiFn.invoke(MultiFn.java:243)
	at clojure.tools.deps.alpha$expand_deps.invokeStatic(alpha.clj:155)
	at clojure.tools.deps.alpha$expand_deps.invoke(alpha.clj:137)
	at clojure.tools.deps.alpha$resolve_deps.invokeStatic(alpha.clj:191)
	at clojure.tools.deps.alpha$resolve_deps.invoke(alpha.clj:182)
	at mach.pack.alpha.aws_lambda$_main.invokeStatic(aws_lambda.clj:63)
	at mach.pack.alpha.aws_lambda$_main.doInvoke(aws_lambda.clj:56)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not find artifact net.java:jvnet-parent:pom:3 in glassfish-repository (http://download.java.net/maven/glassfish)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:177)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:226)
	at org.apache.maven.model.building.DefaultModelBuilder.readParentExternally(DefaultModelBuilder.java:1000)
	at org.apache.maven.model.building.DefaultModelBuilder.readParent(DefaultModelBuilder.java:800)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:329)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:320)
	... 20 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact net.java:jvnet-parent:pom:3 in glassfish-repository (http://download.java.net/maven/glassfish)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:422)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:224)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:201)
	at org.apache.maven.repository.internal.DefaultModelResolver.resolveModel(DefaultModelResolver.java:173)
	... 25 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact net.java:jvnet-parent:pom:3 in glassfish-repository (http://download.java.net/maven/glassfish)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:365)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:583)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:259)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:498)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:399)
	... 28 more
```

I'm at a loss on how to troubleshoot– any help greatly appreciated.

**Comment by SevereOverfl0w** [comment]
Odd. I have a suspicion that running `clj -R:pack` once may fix it, but I'm not certain.

What is your intention by having that dependency in the `pack` alias? That won't add it to your uberjar, only for the uberjar.

**Comment by SevereOverfl0w** [comment]
Do you have `:mvn/repos` set somewhere? It looks like it's trying to download the dependency from `http://download.java.net/maven/glassfish` rather than Maven Central.

**Comment by SevereOverfl0w** [comment]
I ran your deps.edn file, and noticed an unrelated bug in the lambda generator, so make sure you're on `1d455f6c591f440560c57a29e6d930004d735dcf`, the new injector command in the README can be run to auto-update.

After fixing that bug, I was able to generate a lambda zip though, with no dependency resolution issues. I have a strong suspicion this is related to your repos setting. Pack doesn't look at `~/.clojure/deps.edn` or `/usr/lib/clojure/deps.edn` though, so I am not sure how a `:mvn/repos` setting is leaking in.

**Comment by solussd** [comment]
Thanks for the response–– the extra dependency in the pack extra-deps is a red herring. It still happens if I remove it (that was left over from an attempt at working around the issue).

The dependency that appears to be causing this is: `javax.servlet/javax.servlet-api 3.1.0`. Adding just that reproduces the error for me.

I have no repo setting in settings.xml or ~/.clojure/deps.edn.

**Comment by solussd** [comment]
@SevereOverfl0w Here's a repo for testing: https://github.com/solussd/blah
I have a coworker that was able to reproduce the error, which leads me to speculate that you might already have the missing dep in your maven cache. Could you try again after moving your existing maven cache out of the way with the repo above?

**Comment by SevereOverfl0w** [comment]
I was able to reproduce by removing my m2 cache. This is very strange, I'd been able to rely on `clj` fetching the same things as tools.deps.alpha deps.edn would alone.

The workaround is the same though, add:

```
:mvn/repos {"central" {:url "https://repo1.maven.org/maven2/"}
             "clojars" {:url "https://repo.clojars.org/"}}
```

to your deps.edn file.

**Comment by solussd** [comment]
I figured out where the glassfish repo was being used: `~/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom`

with this fun little comment:
```
    <!-- for downloading org.glassfish:legal:1.1 resource bundle      -->
    <!-- referenced in maven-remote-resources-plugin.  Will           -->
    <!-- remove the repositories element once org.glassfish:legal:1.1 -->
    <!-- is available in the central repo.                                      -->
    <repositories>
        <repository>
            <id>glassfish-repository</id>
            <url>http://download.java.net/maven/glassfish</url>
            <snapshots>
                <updatePolicy>never</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
```

Worked around by commenting out the repository element, but the real fix is likely in a newer version of javax.servlet-api.

Thanks for investigating, closing.
